### PR TITLE
I believe a lot of the explanations were wrong so these are my propos…

### PR DESCRIPTION
**Pull request by gubuntu**
…ed corrections

### CODE REVIEW

**Comment by Samweli** [comment]
@vermeulendivan can you add your review for these changes.

**Comment by vermeulendivan** [comment]
@Samweli I've checked it, and the suggested changes is correct for the upstream/downstream changes. other changes is just minor.
image

**Comment by vermeulendivan** [comment]
i will have to apply these changes to the sphinx docs as those definitions comes from the original sphinx docs. will PR a branch shortly

**Review by vermeulendivan — APPROVED** [review]
Had a look at this, and changes correct. Upstream/downstream has been swapped in the original definitions, so these changes is perfect. See other comments for details.

**Comment by Samweli** [comment]
thanks @gubuntu and @vermeulendivan

**Pull request merged**
